# Generated by Django 3.1.1 on 2021-03-12 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('file_url', models.FileField(null=True, upload_to='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_points', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('credit', models.IntegerField(default=0)),
                ('assign_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.coursesem')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveIntegerField(max_length=3)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.coursesem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField()),
                ('ans_url', models.FileField(upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('marks', models.PositiveIntegerField(null=True)),
                ('done_status', models.CharField(max_length=100)),
                ('que_ass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.assignment')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendancedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=0)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropwork.subject')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.coursesem'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.teacher'),
        ),
    ]
