# Generated by Django 3.1.1 on 2021-03-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='midtermmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateTimeField()),
                ('outofmid', models.PositiveIntegerField()),
                ('midtermmarks', models.PositiveIntegerField()),
                ('outofinternal', models.PositiveIntegerField()),
                ('internalmarks', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=0)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropwork.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dropwork.subject')),
            ],
        ),
    ]
