# Generated by Django 3.1.1 on 2021-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropwork', '0002_midtermmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermmarks',
            name='month',
            field=models.CharField(default='MAR', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midtermmarks',
            name='year',
            field=models.CharField(default=2021, max_length=50),
            preserve_default=False,
        ),
    ]
