# Generated by Django 3.1.1 on 2021-03-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropwork', '0004_remove_midtermmarks_result_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midtermmarks',
            old_name='midtermmarks',
            new_name='midtermmark',
        ),
        migrations.RemoveField(
            model_name='midtermmarks',
            name='status',
        ),
    ]
